name = "Seis4CCS"
uuid = "808f26ee-2243-4b28-9f59-2530de529097"
authors = ["Ziyi (Francis) Yin <ziyi.yin@gatech.edu> and SLIM contributors"]
version = "0.1.0"

[deps]
FwiFlow = "a6a960b4-e246-4968-83bc-819d1955448a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FwiFlow = "0.2, 0.3"
julia = "1"